mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import RedirectView
from polls import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path('polls/', include('polls.urls')),
    path('', RedirectView.as_view(url = 'polls/')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('signup/', views.signup, name = "signup")
]

polls/urls.py
from django.urls import path
from . import views


app_name = "polls"

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

polls/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


# Create your models here.


class Question(models.Model):
    """
    Represents a poll question.

    Attributes:
        question_text (str): The text of the question being asked.
        pub_date (datetime): The date and time when the question was published.
        end_date (datetime): The date and time when the question
            will end (optional).
    """

    question_text = models.CharField(max_length=250)
    pub_date = models.DateTimeField("date published", default=timezone.now)
    end_date = models.DateTimeField("date ended", null=True)

    def is_published(self):
        """
        Checks if the question has been published.

        Returns:
            bool: True if the current date and time is after the
                publication date.
        """
        now = timezone.now()
        return self.pub_date <= now

    def can_vote(self):
        """
        Determines if the question is currently open for voting.

        Returns:
            bool: True if the current date and time is within the
                  publication and end dates, or if there is no end date.
        """
        now = timezone.now()
        if self.end_date is not None:
            return self.pub_date <= now <= self.end_date
        return self.pub_date <= now

    def was_published_recently(self):
        """
        Determines if the question was published within the last day.

        Returns:
            bool: True if the question's publication date is within
                  the last day, False otherwise.
        """
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    def __str__(self):
        """
        Returns a string representation of the Question instance.

        Returns:
            str: A formatted string showing the question's ID, text,
                 and publication date.
        """
        return (
            f"Question ID: {self.id}, Question: {self.question_text}, "
            f"Published on: {self.pub_date}"
        )


class Choice(models.Model):
    """
    Represents a choice for a poll question.

    Attributes:
        question (Question): The question to which this choice belongs.
        choice_text (str): The text of the choice.
        vote (int): The number of votes this choice has received.
    """

    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=250)

    @property
    def vote(self):
        return Vote.objects.filter(choice=self).count()

    def __str__(self):
        """
        Returns a string representation of the Choice instance.

        Returns:
            str: The text of the choice.
        """
        return f"Choice ID: {self.id}, Choice: {self.choice_text}, "


class Vote(models.Model):
    """A vote by a user for a choice in a poll"""

    choice = models.ForeignKey(Choice, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"Choice: {self.choice}, User: {self.user}"

polls/views.py
import logging
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render, redirect
from django.http import Http404, HttpResponseRedirect
from django.contrib.auth.signals import (
    user_logged_in,
    user_logged_out,
    user_login_failed,
)
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.dispatch import receiver
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.contrib import messages
from .models import Question, Choice, Vote


def get_client_ip(request):
    """Get the visitor’s IP address using request headers."""
    if (request is None):
        return False
    x_forwarded_for = request.META.get("HTTP_X_FORWARDED_FOR")
    if x_forwarded_for:
        ip_address = x_forwarded_for.split(",")[0]
    else:
        ip_address = request.META.get("REMOTE_ADDR")
    return ip_address


@receiver(user_login_failed)
def log_user_login_failed(request, credentials, **kwargs):
    """
    Get the signal, when user failed login.
    """
    logger = logging.getLogger("polls")
    ip = get_client_ip(request)
    username = credentials.get("username", None)
    logger.warning(f"Failed login for {username} from {ip}")


@receiver(user_logged_in)
def log_user_login(request, user, **kwargs):
    """
    Get the signal, when user logged in.
    """
    logger = logging.getLogger("polls")
    ip_address = get_client_ip(request)
    logger.info(f'User "{user.username}" logged in from IP {ip_address}.')


@receiver(user_logged_out)
def log_user_logout(request, user, **kwargs):
    """
    Get the signal, when user logged out.
    """
    logger = logging.getLogger("polls")
    ip_address = get_client_ip(request)
    logger.info(f'User "{user.username}" logged out from IP {ip_address}.')


class IndexView(generic.ListView):
    """
    View to display the list of the most recent questions.
    """

    template_name = "polls/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        """
        Returns the last five published questions (excluding future questions).
        """
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by(
            "-pub_date"
        )


class DetailView(generic.DetailView):
    """
    Display the contents of a specific question and allow voting.
    """

    model = Question
    template_name = "polls/detail.html"

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())

    def get_context_data(self, **kwargs):
        """
        Get the context data for the view.
        """
        context = super().get_context_data(**kwargs)
        self.object = self.get_object()
        vote = None
        if self.request.user.is_authenticated:
            try:
                vote = Vote.objects.get(
                    user=self.request.user, choice__question=self.object
                )
            except Vote.DoesNotExist:
                vote = None
        context["vote"] = vote
        return context

    def get(self, request, *args, **kwargs):
        """
        Handles GET requests to display the details of a specific question.

        Args:
            request (HttpRequest): The request object.
            *args: Variable length argument list.
            **kwargs: Keyword arguments including,
            the primary key of the question.

        Returns:
            HttpResponse: The rendered response with question details.
        """
        try:
            self.object = get_object_or_404(Question, pk=kwargs["pk"])
        except Http404:
            messages.error(
                request, f"Poll number with ID {kwargs['pk']} is not available"
            )
            logging.error(f"This question {self.object.pk} does not exist")
            return redirect("polls:index")

        if not self.object.can_vote():
            messages.error(
                request,
                f"Poll number {self.object.pk} has ended, "
                f"which is not allowed for voting.",
            )
            return redirect("polls:index")

        if not self.object.is_published():
            messages.error(
                request, f"Poll number {self.object.pk} " f"is not available"
            )
            return redirect("polls:index")

        if self.request.user.is_authenticated:
            context = self.get_context_data()
            return render(request, "polls/detail.html", context=context)

        return render(request, "polls/detail.html", {"question": self.object})


class ResultsView(generic.DetailView):
    """
    View to display the results of a specific question.
    """

    model = Question
    template_name = "polls/results.html"


@login_required
def vote(request, question_id):
    """
    Handles voting for a specific question.

    Args:
        request (HttpRequest): The request object.
        question_id (int): The ID of the question being voted on.

    Returns:
        HttpResponse: Redirect to the results page
        or re-render voting form with an error message.
    """
    question = get_object_or_404(Question, pk=question_id)
    this_user = request.user
    logger = logging.getLogger(__name__)
    ip_address = get_client_ip(request)
    logger.info(f"{this_user} log in from {ip_address}")

    # The question has ended already
    if not question.can_vote():
        messages.error(
            request,
            f"Poll number {question.id}  " f"is unavailable for voting.",
        )
        logger.warning("This question is not yet voted")
        return HttpResponseRedirect(reverse("polls:index"))

    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        messages.error(request, "You didn't select a choice.")
        logger.warning(f"{this_user} didn't select a choice "
                       f"" f"from {ip_address}."
                       )
        return render(
            request,
            "polls/detail.html",
            {
                "question": question,
            },
        )

    vote_for_poll(request, question.id, logger, selected_choice, this_user)
    return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))


def vote_for_poll(request, question_id, logger, selected_choice, this_user):
    """
    Handles voting for a specific question.
    """
    choice_id = request.POST["choice"]
    question = get_object_or_404(Question, pk=question_id)
    if not choice_id:
        # no choice_id was set
        messages.error(request, "You didn't make a choice")
        return redirect("polls:detail", question_id)
    try:
        vote = this_user.vote_set.get(user=this_user,
                                      choice__question=question
                                      )
        vote.choice = selected_choice
        vote.save()
        messages.success(
            request, f"Your vote for {selected_choice} " f"has been recorded."
        )
        logger.info(
            f"{this_user.username} has voted for {question.id} "
            f"with {choice_id}"
        )
    except Vote.DoesNotExist:
        vote = Vote.objects.create(user=this_user, choice=selected_choice)
        vote.save()
        messages.success(
            request, f"Your vote for {selected_choice} " f"has been recorded."
        )
        logger.info(
            f"{this_user.username} has voted for {question.id} "
            f"with {choice_id}"
        )
    return redirect("polls:results", question_id)


def signup(request):
    """Register a new user."""
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            # get named fields from the form data
            username = form.cleaned_data.get("username")
            # password input field is named 'password1'
            raw_passwd = form.cleaned_data.get("password1")
            user = authenticate(username=username, password=raw_passwd)
            login(request, user)
            return redirect("polls:index")
        else:
            messages.error(request, "Your register is invalid")
            return redirect("signup")
    else:
        # create a user form and display it the signup page
        form = UserCreationForm()
    return render(request, "registration/signup.html", {"form": form})

polls/templates/polls/base.html
{% load static %}
<link rel="stylesheet" href="{% static 'polls/style.css' %}">
<header>
<div>
    {% if user.is_authenticated %}
        Welcome, back {{ user.username }}
        <form action="{% url 'logout' %}" method="post">
        {% csrf_token %}
        <button type="submit">Log Out</button>
        </form>
    {% else %}
        Please <a href="{% url 'login' %}?next={{request.path}}" class = "login-link">Login</a>
        <a href = "{% url 'signup' %}?next ={{ request.path }}" class = "register-link"> signup</a>
    {% endif %}
</div>
</header>
{% block content %}

{% endblock %}

polls/templates/polls/detail.html
{% extends 'polls/base.html' %}
{% block content %}
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <p{% if message.error.tags %} class="{{ message.error.tags }}"{% endif %}>{{ message }}</p>
                {% endfor %}
            </ul>
            {% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}"
            {% if vote.choice_id == choice.id %}checked{% endif %}>
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
    </form>
<li><a href = "{% url 'polls:index'%}">Back to List of Polls</a></li>
<li><a href = "{% url 'polls:results' question.id%}"> See the results</a></li>
{% endblock %}

polls/templates/polls/index.html
{% extends 'polls/base.html' %}
{% load static %}
<link rel="stylesheet" href="{% static 'polls/style.css' %}">

{% block content %}
    <h1>KU Polls</h1>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
        {% endfor %}
    </ul>
    {% endif %}

    {% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
        <li>
            <a href="{% url 'polls:detail' question.id %}">Question {{ question.id }}: {{ question.question_text }}</a>
            <br>
            <a href="{% url 'polls:results' question.id %}" class="view-results"> - See the results of Question {{ question.id }}</a>
            <div class="status-text {% if question.can_vote %}active{% else %}inactive{% endif %}">
                Status: {% if question.can_vote %}Active{% else %}Inactive{% endif %}
            </div>
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <p>No polls are available.</p>
    {% endif %}
{% endblock %}

polls/templates/polls/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Voting Results</title>
    {% extends 'polls/base.html' %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
</head>
{% block content %}
<body>
    <h1>Voting Results for "{{ question.question_text }}"</h1>
    {% if messages %}
    <ul class="messages">
    {% for message in messages %}
    <p{% if message.tags %} class="{{ message.tags}}"{% endif %}>{{ message }}</p>
    {% endfor %}
    {% endif %}
</ul>
    <table class="results-content">
        <thead>
            <tr>
                <th>Choice</th>
                <th>Vote</th>
            </tr>
        </thead>
        <tbody>
            {% for choice in question.choice_set.all%}
                <tr>
                    <td> {{choice.choice_text}}</td>
                    <td class=" vote-count"> {{choice.vote}}</td>
                </tr>
            {% endfor %}
            </tr>
        </tbody>
    </table>
    <a href="{% url 'polls:index' %}">Back to Polls</a>
</body>
</html>
{% endblock %}